package com.suivipredication.app;
import android.app.Activity;import android.content.ContentValues;import android.content.Intent;import android.net.Uri;import android.os.Bundle;import android.os.Environment;import android.provider.MediaStore;import android.webkit.JavascriptInterface;import android.webkit.ValueCallback;import android.webkit.WebChromeClient;import android.webkit.WebSettings;import android.webkit.WebView;import android.webkit.WebViewClient;import android.widget.Toast;import java.io.OutputStream;import java.nio.charset.StandardCharsets;
public class MainActivity extends Activity{
 private WebView webView; private ValueCallback<Uri[]> fileCallback; private static final int FILE_CHOOSER=4512;
 @Override protected void onCreate(Bundle b){super.onCreate(b);webView=new WebView(this);setContentView(webView);WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setDatabaseEnabled(true);webView.setWebViewClient(new WebViewClient());webView.addJavascriptInterface(new Bridge(),"AndroidBridge");webView.setWebChromeClient(new WebChromeClient(){@Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams p){if(fileCallback!=null)fileCallback.onReceiveValue(null);fileCallback=cb;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/json","text/plain","application/octet-stream"});startActivityForResult(i,FILE_CHOOSER);return true;}});webView.loadUrl("file:///android_asset/www/index.html");}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==FILE_CHOOSER&&fileCallback!=null){Uri[] x=null;if(c==RESULT_OK&&d!=null&&d.getData()!=null)x=new Uri[]{d.getData()};fileCallback.onReceiveValue(x);fileCallback=null;}}
 @Override public void onBackPressed(){if(webView!=null&&webView.canGoBack())webView.goBack();else super.onBackPressed();}
 private class Bridge{
  @JavascriptInterface public void exportBackup(String json,String filename){runOnUiThread(()->{try{ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,filename);v.put(MediaStore.Downloads.MIME_TYPE,"application/json");v.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS+"/SuiviPredication");Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u==null)throw new Exception();try(OutputStream o=getContentResolver().openOutputStream(u)){if(o==null)throw new Exception();o.write(json.getBytes(StandardCharsets.UTF_8));}Toast.makeText(MainActivity.this,"Sauvegarde enregistrée dans Téléchargements/SuiviPredication",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(MainActivity.this,"Impossible d’enregistrer la sauvegarde.",Toast.LENGTH_LONG).show();}});}
  @JavascriptInterface public void shareText(String title,String text){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_SUBJECT,title);i.putExtra(Intent.EXTRA_TEXT,text);startActivity(Intent.createChooser(i,"Partager le rapport"));});}
 }
}
